# Generated by Django 4.0.8 on 2023-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
