# Generated by Django 4.0.8 on 2023-09-15 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='reg_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
