# Generated by Django 4.0.8 on 2023-09-16 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_event_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='reg_users_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
