# Generated by Django 4.0.8 on 2023-09-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_team_registered_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
