# Generated by Django 4.0.8 on 2023-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstract_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/'),
        ),
    ]
