# Generated by Django 4.0.8 on 2023-09-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_team_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.AddField(
            model_name='team',
            name='registered_events',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='events.event'),
        ),
    ]
