# Generated by Django 4.0.8 on 2023-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_team_event_team_registered_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='teams', to='events.event'),
        ),
    ]
